# N_ITER_CHEAP       = 10
N_ITER_CHEAP       = 50
# N_ITER_CHEAP       = 20
# N_ITER_CHEAP       = 200
N_ITER_EXACT       = 50
# EM_ITER_CHEAP      = 1
# EM_ITER_CHEAP      = 5
# EM_ITER_CHEAP      = 10
EM_ITER_CHEAP      = 50
DEFAULT_LAMBDA     = (.1, .0001)
# DEFAULT_LAMBDA     = (10, .001)
MAX_CLD_SIZE       = 150
MAX_TRAJ_LEN       = 150
EXACT_LAMBDA       = (10, .001)
DATA_DIM           = 3
# DS_SIZE            = 0.025
# DS_SIZE            = 0.015
DS_SIZE            = 0.02
N_STREAMS          = 10
DEFAULT_NORM_ITERS = 10
# DEFAULT_NORM_ITERS = 50
BEND_COEF_DIGITS   = 6
